name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "CYPRESS_USERNAME=${{ secrets.CYPRESS_USERNAME }}" >> .env
          echo "CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }}" >> .env

      - name: Run Cypress tests
        run: npx cypress run